# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Duplicator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setItalic(False)
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(True)
        MainWindow.setStyleSheet("QMainWindow{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.977273, y2:0.989, stop:0 rgba(255, 255, 127, 255), stop:0.875 rgba(255, 255, 255, 255));}\n"
"QMainWindow{background-color: rgb(240, 240, 240);}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 30, 801, 51))
        self.label.setStyleSheet("font: 26pt \"Reem Kufi\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(500, 130, 20, 421))
        self.line.setStyleSheet("color: rgb(0, 0, 0);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(0)
        self.line.setMidLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.server = QtWidgets.QComboBox(self.centralwidget)
        self.server.setGeometry(QtCore.QRect(70, 140, 320, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.server.setFont(font)
        self.server.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.server.setStyleSheet("border:1px solid;\n"
"border-radius: 4px;")
        self.server.setEditable(False)
        self.server.setObjectName("server")
        self.server.addItem("")
        self.server.addItem("")
        self.server.addItem("")
        self.browse_folder = QtWidgets.QPushButton(self.centralwidget)
        self.browse_folder.setGeometry(QtCore.QRect(400, 290, 75, 23))
        self.browse_folder.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 157, 235);\n"
"}\n"
"QPushButton:hover{background-color: rgb(85, 170, 255);}\n"
"\n"
"")
        self.browse_folder.setObjectName("browse_folder")
        self.dnd = FileEdit(self.centralwidget)
        self.dnd.setGeometry(QtCore.QRect(70, 210, 320, 170))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        self.dnd.setFont(font)
        self.dnd.setStyleSheet("border:1px solid;\n"
"border-radius: 4px;\n"
"")
        self.dnd.setAlignment(QtCore.Qt.AlignCenter)
        self.dnd.setObjectName("dnd")
        self.browse_path = QtWidgets.QPushButton(self.centralwidget)
        self.browse_path.setGeometry(QtCore.QRect(400, 490, 75, 23))
        self.browse_path.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 157, 235);\n"
"}\n"
"QPushButton:hover{background-color: rgb(85, 170, 255);}")
        self.browse_path.setObjectName("browse_path")
        self.path = QtWidgets.QLineEdit(self.centralwidget)
        self.path.setGeometry(QtCore.QRect(70, 490, 320, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.path.setFont(font)
        self.path.setStyleSheet("border:1px solid;\n"
"border-radius: 4px;\n"
"")
        self.path.setObjectName("path")
        self.label_progress = QtWidgets.QLabel(self.centralwidget)
        self.label_progress.setGeometry(QtCore.QRect(510, 140, 291, 41))
        self.label_progress.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_progress.setAlignment(QtCore.Qt.AlignCenter)
        self.label_progress.setObjectName("label_progress")
        self.label_progress_num = QtWidgets.QLabel(self.centralwidget)
        self.label_progress_num.setGeometry(QtCore.QRect(510, 180, 291, 41))
        self.label_progress_num.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_progress_num.setAlignment(QtCore.Qt.AlignCenter)
        self.label_progress_num.setObjectName("label_progress_num")
        self.number = QtWidgets.QLineEdit(self.centralwidget)
        self.number.setGeometry(QtCore.QRect(604, 360, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.number.setFont(font)
        self.number.setStyleSheet("border:1px solid;\n"
"border-radius: 4px;\n"
"")
        self.number.setAlignment(QtCore.Qt.AlignCenter)
        self.number.setObjectName("number")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(510, 320, 291, 31))
        self.label_4.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(560, 490, 91, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.start.setFont(font)
        self.start.setStyleSheet("QPushButton{background-color: rgb(0, 255, 127);\n"
"color: rgb(0, 0, 0);}\n"
"QPushButton:hover{background-color: rgb(170, 255, 127);}\n"
"\n"
"\n"
"")
        self.start.setObjectName("start")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 190, 221, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 470, 221, 21))
        self.label_6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.diskspace = QtWidgets.QLabel(self.centralwidget)
        self.diskspace.setGeometry(QtCore.QRect(70, 520, 271, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.diskspace.setFont(font)
        self.diskspace.setStyleSheet("")
        self.diskspace.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.diskspace.setObjectName("diskspace")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 385, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName("label_7")
        self.folder_name = QtWidgets.QLineEdit(self.centralwidget)
        self.folder_name.setGeometry(QtCore.QRect(70, 405, 320, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.folder_name.setFont(font)
        self.folder_name.setStyleSheet("border:1px solid;\n"
"border-radius: 4px;\n"
"")
        self.folder_name.setObjectName("folder_name")
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setGeometry(QtCore.QRect(670, 490, 91, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("QPushButton{background-color: rgb(255, 0, 0);\n"
"color: rgb(0, 0, 0);}\n"
"QPushButton:hover{background-color: rgb(255, 85, 127);}\n"
"\n"
"")
        self.cancel.setObjectName("cancel")
        self.foldersize = QtWidgets.QLabel(self.centralwidget)
        self.foldersize.setGeometry(QtCore.QRect(70, 435, 271, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.foldersize.setFont(font)
        self.foldersize.setStyleSheet("")
        self.foldersize.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.foldersize.setObjectName("foldersize")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(605, 230, 131, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.reset1 = QtWidgets.QPushButton(self.centralwidget)
        self.reset1.setGeometry(QtCore.QRect(400, 405, 75, 23))
        self.reset1.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 157, 235);\n"
"}\n"
"QPushButton:hover{background-color: rgb(85, 170, 255);}\n"
"\n"
"")
        self.reset1.setObjectName("reset1")
        self.reset2 = QtWidgets.QPushButton(self.centralwidget)
        self.reset2.setGeometry(QtCore.QRect(400, 520, 75, 23))
        self.reset2.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 157, 235);\n"
"}\n"
"QPushButton:hover{background-color: rgb(85, 170, 255);}\n"
"\n"
"")
        self.reset2.setObjectName("reset2")
        self.max_copies = QtWidgets.QLabel(self.centralwidget)
        self.max_copies.setGeometry(QtCore.QRect(520, 400, 271, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.max_copies.setFont(font)
        self.max_copies.setStyleSheet("")
        self.max_copies.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.max_copies.setObjectName("max_copies")
        self.needed_space = QtWidgets.QLabel(self.centralwidget)
        self.needed_space.setGeometry(QtCore.QRect(520, 425, 271, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.needed_space.setFont(font)
        self.needed_space.setStyleSheet("")
        self.needed_space.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.needed_space.setObjectName("needed_space")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Folder Duplicator"))
        self.server.setCurrentText(_translate("MainWindow", "--Choose Server--"))
        self.server.setItemText(0, _translate("MainWindow", "--Choose Server--"))
        self.server.setItemText(1, _translate("MainWindow", "VDSPC"))
        self.server.setItemText(2, _translate("MainWindow", "V-Lib"))
        self.browse_folder.setText(_translate("MainWindow", "Browse..."))
        self.dnd.setText(_translate("MainWindow", "Drag and Drop"))
        self.browse_path.setText(_translate("MainWindow", "Browse..."))
        self.label_progress.setText(_translate("MainWindow", "Welcome!"))
        self.label_progress_num.setText(_translate("MainWindow", "-"))
        self.number.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "Number of copies:"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.label_5.setText(_translate("MainWindow", "Choose a source to duplicate:"))
        self.label_6.setText(_translate("MainWindow", "Output Directory:"))
        self.diskspace.setText(_translate("MainWindow", "Free space: -"))
        self.label_7.setText(_translate("MainWindow", "Folder/File selected:"))
        self.cancel.setText(_translate("MainWindow", "Cancel"))
        self.foldersize.setText(_translate("MainWindow", "Folder/File size: -"))
        self.reset1.setText(_translate("MainWindow", "Reset"))
        self.reset2.setText(_translate("MainWindow", "Reset"))
        self.max_copies.setText(_translate("MainWindow", "Maximum number of copies: -"))
        self.needed_space.setText(_translate("MainWindow", "Space needed: -"))
from FileEdit import FileEdit


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
