# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vlib_path.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 121)
        font = QtGui.QFont()
        font.setPointSize(7)
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(500, 0, 81, 121))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 22, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 52, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 82, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pgmpath = QtWidgets.QLineEdit(Dialog)
        self.pgmpath.setGeometry(QtCore.QRect(120, 82, 291, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pgmpath.setFont(font)
        self.pgmpath.setObjectName("pgmpath")
        self.ocvpath = QtWidgets.QLineEdit(Dialog)
        self.ocvpath.setGeometry(QtCore.QRect(120, 52, 291, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ocvpath.setFont(font)
        self.ocvpath.setObjectName("ocvpath")
        self.partpath = QtWidgets.QLineEdit(Dialog)
        self.partpath.setGeometry(QtCore.QRect(120, 22, 291, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.partpath.setFont(font)
        self.partpath.setObjectName("partpath")
        self.browsepart = QtWidgets.QPushButton(Dialog)
        self.browsepart.setGeometry(QtCore.QRect(420, 20, 61, 20))
        self.browsepart.setStyleSheet("\n"
"\n"
"")
        self.browsepart.setObjectName("browsepart")
        self.browseocv = QtWidgets.QPushButton(Dialog)
        self.browseocv.setGeometry(QtCore.QRect(420, 50, 61, 20))
        self.browseocv.setStyleSheet("")
        self.browseocv.setObjectName("browseocv")
        self.browsepgm = QtWidgets.QPushButton(Dialog)
        self.browsepgm.setGeometry(QtCore.QRect(420, 80, 61, 20))
        self.browsepgm.setStyleSheet("")
        self.browsepgm.setObjectName("browsepgm")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Part Library:"))
        self.label_2.setText(_translate("Dialog", "OCV Library:"))
        self.label_3.setText(_translate("Dialog", "Program Library:"))
        self.browsepart.setText(_translate("Dialog", "Browse..."))
        self.browseocv.setText(_translate("Dialog", "Browse..."))
        self.browsepgm.setText(_translate("Dialog", "Browse..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
